# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='menu',
        ),
        migrations.AddField(
            model_name='permission',
            name='menus',
            field=models.ManyToManyField(to='rbac.Menu'),
        ),
    ]
