# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20180702_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='role_id',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='userrole',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menu_id',
        ),
        migrations.RemoveField(
            model_name='role',
            name='role_id',
        ),
        migrations.AddField(
            model_name='menu',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
